#Pandas Series and DataFrames
- Difference
- Usage

In [1]:
import pandas as pd
s = pd.Series([1,2,3,4,5])

s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
s.shape

(5,)

In [3]:
type(s)

pandas.core.series.Series

In [4]:
s.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [5]:
s.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [6]:
s.head(2)

0    1
1    2
dtype: int64

In [7]:
s.columns

AttributeError: 'Series' object has no attribute 'columns'

In [8]:
s.dtypes

dtype('int64')

In [9]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#s['column_name']

In [10]:
s+2

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [13]:
s=s*2

In [14]:
s

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [15]:
temp = pd.Series([25,28,19,20,29])
rain_chances = pd.Series([30,45,80,20,67])

df = pd.DataFrame()
df['Temp'] = temp
df['Rain_Chances'] = rain_chances

df

   Temp  Rain_Chances
0    25            30
1    28            45
2    19            80
3    20            20
4    29            67

In [16]:
df

   Temp  Rain_Chances
0    25            30
1    28            45
2    19            80
3    20            20
4    29            67

In [18]:
type(df['Temp'])

pandas.core.series.Series

In [19]:
df

   Temp  Rain_Chances
0    25            30
1    28            45
2    19            80
3    20            20
4    29            67

In [23]:
#fetch data from row number 2

df[df.index==2]

   Temp  Rain_Chances
2    19            80

In [24]:
#fetch data from row number 2 and 3 both
df[(df.index==2) | (df.index==3)]

   Temp  Rain_Chances
2    19            80
3    20            20

In [25]:
df

   Temp  Rain_Chances
0    25            30
1    28            45
2    19            80
3    20            20
4    29            67

In [27]:
df.loc[2:4]

   Temp  Rain_Chances
2    19            80
3    20            20
4    29            67

In [28]:
path='/content/ecommerce_product_performance.csv'
df = pd.read_csv(path)
df.head()

,Product_Price,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID
0,199.671415,0.177024,4.411071,62.0,1.0,9.0,0.185116,5.0
1,136.173570,0.041467,3.033534,201.0,1.0,3.0,0.384639,10.0
2,214.768854,0.276197,2.866881,479.0,1.0,19.0,0.056410,4.0
3,302.302986,0.094254,4.473473,252.0,1.0,11.0,NaN,7.0
4,126.584663,0.411845,3.553082,671.0,1.0,14.0,0.672163,6.0

In [30]:
#fetch rows 3 through 10

df.loc[3:10]['Product_Rating']

3     4.473473
4     3.553082
5     1.874022
6          NaN
7     3.366010
8     5.000000
9     5.000000
10    2.798990
Name: Product_Rating, dtype: float64

In [31]:
df.loc[3:10][['Product_Rating','Number_of_Reviews']]

    Product_Rating  Number_of_Reviews
3         4.473473              252.0
4         3.553082              671.0
5         1.874022              303.0
6              NaN              350.0
7         3.366010              330.0
8         5.000000              179.0
9         5.000000              350.0
10        2.798990                NaN

In [33]:
df.head(2)

,Product_Price,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID
0,199.671415,0.177024,4.411071,62.0,1.0,9.0,0.185116,5.0
1,136.173570,0.041467,3.033534,201.0,1.0,3.0,0.384639,10.0

In [37]:
df.loc[[3,4],['Product_Rating']]

   Product_Rating
3        4.473473
4        3.553082

In [38]:
df.head()

,Product_Price,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID
0,199.671415,0.177024,4.411071,62.0,1.0,9.0,0.185116,5.0
1,136.173570,0.041467,3.033534,201.0,1.0,3.0,0.384639,10.0
2,214.768854,0.276197,2.866881,479.0,1.0,19.0,0.056410,4.0
3,302.302986,0.094254,4.473473,252.0,1.0,11.0,NaN,7.0
4,126.584663,0.411845,3.553082,671.0,1.0,14.0,0.672163,6.0

In [40]:
#Number_of_Reviews>200

df[df['Number_of_Reviews']>200]

,Product_Price,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID
1,136.173570,0.041467,3.033534,201.0,1.0,3.0,0.384639,10.0
2,214.768854,0.276197,2.866881,479.0,1.0,19.0,0.056410,4.0
3,302.302986,0.094254,4.473473,252.0,1.0,11.0,NaN,7.0
4,126.584663,0.411845,3.553082,671.0,1.0,14.0,0.672163,6.0
5,126.586304,0.515701,1.874022,303.0,NaN,2.0,0.114370,7.0
...,...,...,...,...,...,...,...,...
1992,NaN,0.256828,3.495332,343.0,0.0,20.0,0.160149,4.0
1995,257.015024,0.098708,3.805205,398.0,1.0,7.0,NaN,5.0
1996,NaN,0.679901,3.340395,788.0,NaN,17.0,0.195181,10.0
1997,61.812535,0.081616,2.736741,297.0,1.0,7.0,0.293520,7.0
1998,133.693304,0.346151,3.246759,467.0,1.0,6.0,0.362834,8.0

In [42]:
df[(df['Number_of_Reviews']>200) & (df['Product_Rating']>4)]

,Product_Price,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID
3,302.302986,0.094254,4.473473,252.0,1.0,11.0,NaN,7.0
9,204.256004,0.301962,5.000000,350.0,1.0,20.0,0.480863,8.0
11,103.427025,0.277367,4.833190,589.0,1.0,NaN,0.338990,4.0
18,NaN,0.174789,4.943566,454.0,1.0,3.0,0.168136,3.0
25,161.092259,0.085522,4.191829,314.0,1.0,11.0,0.275733,NaN
...,...,...,...,...,...,...,...,...
1965,158.958068,0.235899,5.000000,278.0,1.0,10.0,0.039276,6.0
1968,130.509172,0.152270,4.102972,234.0,1.0,24.0,0.544813,5.0
1979,190.705229,0.332031,4.937858,1675.0,0.0,13.0,0.575769,10.0
1986,222.509579,0.049595,5.000000,771.0,0.0,17.0,0.423582,5.0
1991,225.429133,0.177269,4.479373,260.0,1.0,16.0,0.523464,NaN

In [41]:
df.head()

,Product_Price,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID
0,199.671415,0.177024,4.411071,62.0,1.0,9.0,0.185116,5.0
1,136.173570,0.041467,3.033534,201.0,1.0,3.0,0.384639,10.0
2,214.768854,0.276197,2.866881,479.0,1.0,19.0,0.056410,4.0
3,302.302986,0.094254,4.473473,252.0,1.0,11.0,NaN,7.0
4,126.584663,0.411845,3.553082,671.0,1.0,14.0,0.672163,6.0

In [45]:
df['rating'] = round(df['Product_Rating'])

In [47]:
df.head()

,Product_Price,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID,rating
0,199.671415,0.177024,4.411071,62.0,1.0,9.0,0.185116,5.0,4.0
1,136.173570,0.041467,3.033534,201.0,1.0,3.0,0.384639,10.0,3.0
2,214.768854,0.276197,2.866881,479.0,1.0,19.0,0.056410,4.0,3.0
3,302.302986,0.094254,4.473473,252.0,1.0,11.0,NaN,7.0,4.0
4,126.584663,0.411845,3.553082,671.0,1.0,14.0,0.672163,6.0,4.0

In [48]:
#reorder columns
df.columns

Index(['Product_Price', 'Discount_Rate', 'Product_Rating', 'Number_of_Reviews',
       'Stock_Availability', 'Days_to_Deliver', 'Return_Rate', 'Category_ID',
       'rating'],
      dtype='object')

In [50]:
df=df[['Product_Price','rating' ,'Discount_Rate', 'Product_Rating', 'Number_of_Reviews',
       'Stock_Availability', 'Days_to_Deliver', 'Return_Rate', 'Category_ID',
       ]]

df.head()

,Product_Price,rating,Discount_Rate,Product_Rating,Number_of_Reviews,Stock_Availability,Days_to_Deliver,Return_Rate,Category_ID
0,199.671415,4.0,0.177024,4.411071,62.0,1.0,9.0,0.185116,5.0
1,136.173570,3.0,0.041467,3.033534,201.0,1.0,3.0,0.384639,10.0
2,214.768854,3.0,0.276197,2.866881,479.0,1.0,19.0,0.056410,4.0
3,302.302986,4.0,0.094254,4.473473,252.0,1.0,11.0,NaN,7.0
4,126.584663,4.0,0.411845,3.553082,671.0,1.0,14.0,0.672163,6.0

In [58]:
for row in df.iterrows():
  print(row[1][0],'----',row[1][1])

199.6714153011233 ---- 4.0
136.17356988288154 ---- 3.0
214.76885381006923 ---- 3.0
302.30298564080255 ---- 4.0
126.5846625276664 ---- 4.0
126.58630430508194 ---- 2.0
307.92128155073914 ---- nan
226.74347291529088 ---- 3.0
103.0525614065048 ---- 5.0
204.25600435859647 ---- 5.0
103.65823071875376 ---- 3.0
103.42702464297432 ---- 5.0
174.1962271566034 ---- 3.0
5.0 ---- 2.0
5.0 ---- 3.0
93.77124707590272 ---- 4.0
48.71688796655762 ---- 3.0
181.4247332595274 ---- 3.0
nan ---- 5.0
8.769629866470865 ---- nan
296.56487689215544 ---- 3.0
127.42236995134644 ---- 5.0
156.75282046879238 ---- 4.0
nan ---- 1.0
95.56172754748174 ---- 4.0
161.09225897098662 ---- 4.0
34.90064225776972 ---- 4.0
187.5698018345672 ---- 5.0
89.9361310081195 ---- 3.0
120.83062502067231 ---- 4.0
89.82933877706031 ---- 2.0
335.2278184508938 ---- 4.0
148.6502775262066 ---- 5.0
44.22890710440997 ---- 3.0
232.2544912103189 ---- 3.0
27.915635002897773 ---- 3.0
170.88635950047555 ---- 4.0
5.0 ---- 3.0
17.181395110156956 ---- 4.0
169.68612358691234 ---- 5.0
223.84665799954104 ---- 4.0
167.13682811899704 ---- 2.0
138.43517176117595 ---- 5.0
119.88963044107112 ---- 5.0
5.0 ---- 5.0
78.01557916052914 ---- 4.0
103.93612290402125 ---- 4.0
255.7122226218916 ---- 5.0
nan ---- 5.0
5.0 ---- 3.0
182.4083969394795 ---- 5.0
111.49177195836836 ---- 4.0
82.30779996940413 ---- 4.0
211.1676288840868 ---- nan
253.0999522495951 ---- 4.0
243.12801191161984 ---- 3.0
66.07824767773614 ---- 3.0
119.07876241487854 ---- 3.0
183.1263431403564 ---- 3.0
247.55451271223592 ---- nan
102.082576215471 ---- 4.0
131.43410233361828 ---- 2.0
39.36650259939718 ---- 2.0
30.379337591932924 ---- 4.0
231.2525822394198 ---- 3.0
285.6240028570823 ---- 5.0
nan ---- 4.0
250.3532897892024 ---- 4.0
186.16360250476345 ---- 5.0
85.48802453948757 ---- 3.0
186.1395605508414 ---- 3.0
303.8036566465969 ---- 5.0
146.41739608900485 ---- nan
306.4643655814006 ---- 4.0
5.0 ---- 5.0
232.1902504375224 ---- 4.0
158.70470682381713 ---- 4.0
120.09926495341324 ---- 4.0
159.17607765355024 ---- 3.0
5.0 ---- 4.0
128.0328112162488 ---- 5.0
185.71125715117464 ---- 4.0
297.78940447415164 ---- 4.0
98.17297817263524 ---- 4.0
69.15063971068123 ---- 4.0
99.82429564154634 ---- 5.0
241.5402117702074 ---- nan
182.87511096596845 ---- 3.0
97.02397962329611 ---- 4.0
201.3267433113356 ---- 4.0
159.70775493480403 ---- 3.0
246.8644990532889 ---- 4.0
79.79469061226476 ---- 2.0
117.23378534022318 ---- 4.0
110.78918468678424 ---- 4.0
nan ---- 5.0
179.6120277064576 ---- 3.0
176.10552721798894 ---- 4.0
150.51134566424608 ---- 5.0
126.5412866624853 ---- 5.0
8.46292579495858 ---- 4.0
107.93546772346409 ---- 4.0
115.72854834732306 ---- 5.0
69.77227307783811 ---- 2.0
133.87142883339908 ---- 3.0
190.40508568145384 ---- 5.0
338.618590121053 ---- 5.0
167.4577812831839 ---- 4.0
175.75503907227645 ---- 2.0
142.55540842338328 ---- 4.0
5.0 ---- 3.0
147.34861245507832 ---- 4.0
156.02302099410264 ---- 3.0
396.3242112485286 ---- 3.0
130.76390352188776 ---- 2.0
180.15473423336124 ---- 5.0
146.52882302947566 ---- 3.0
33.1321962380468 ---- 4.0
264.28228145150206 ---- 4.0
225.19330326867745 ---- nan
229.10319470430468 ---- 3.0
59.061254520526106 ---- 3.0
nan ---- 3.0
9.81489372077192 ---- 4.0
208.68570938002705 ---- nan
369.04556258099785 ---- 5.0
50.946367486931166 ---- 5.0
93.3702270397228 ---- 5.0
159.96513650876412 ---- 4.0
99.65243458838007 ---- 5.0
5.0 ---- 4.0
156.85629748060273 ---- 4.0
43.76962862738951 ---- 4.0
197.35924306351816 ---- 5.0
58.05757657661968 ---- nan
304.993440501754 ---- 3.0
71.6746707663763 ---- 3.0
117.79384837943245 ---- 4.0
231.35172173696697 ---- nan
26.913568356604472 ---- 3.0
172.74599346041293 ---- 2.0
280.7142754282428 ---- 4.0
5.0 ---- 4.0
168.46338585323042 ---- 5.0
175.98827942484235 ---- 3.0
228.18228717773104 ---- 3.0
26.3049289121918 ---- 3.0
17.95433869157236 ---- 5.0
202.19415656168977 ---- 4.0
179.6984673233186 ---- 3.0
175.04928503458763 ---- 4.0
184.6448209496976 ---- 3.0
nan ---- 3.0
173.22536971610035 ---- 3.0
179.30724732986812 ---- 5.0
78.56485819736322 ---- 4.0
336.57745111447565 ---- 4.0
197.3832920911788 ---- 4.0
30.86965027973514 ---- 4.0
215.65536086338292 ---- nan
52.531832977267854 ---- 4.0
228.7084603742452 ---- 4.0
265.8595579007404 ---- nan
67.93176816482895 ---- 4.0
246.33761292443216 ---- 3.0
191.27809269364985 ---- 3.0
232.206015999449 ---- nan
339.6792982653948 ---- 5.0
125.46118839971297 ---- 5.0
74.62638356425104 ---- 3.0
61.04855703744767 ---- 4.0
68.41897150345618 ---- 3.0
142.2898290585896 ---- 5.0
184.1151974816644 ---- 2.0
177.6690799330019 ---- 4.0
232.7183249036024 ---- 4.0
151.3001891877907 ---- 5.0
295.3534077157317 ---- 4.0
123.53431667620438 ---- 2.0
422.01691665896186 ---- 4.0
212.56673477650065 ---- 3.0
64.28424435837175 ---- 4.0
42.91075019388877 ---- 5.0
198.24724152431853 ---- 2.0
127.65372146741493 ---- 3.0
221.4000494092092 ---- 3.0
197.3237624573545 ---- 3.0
142.71710873431272 ---- 5.0
65.32062819315951 ---- 4.0
5.0 ---- 4.0
105.34850479329788 ---- nan
235.63987943234724 ---- 4.0
171.4093744130204 ---- 5.0
25.4261221288012 ---- 3.0
167.3180925851182 ---- 5.0
188.5317379728837 ---- 4.0
61.6142563798867 ---- 5.0
165.37251059455278 ---- 4.0
155.8208718446 ---- 4.0
35.702970216937686 ---- 4.0
185.77873603482837 ---- 4.0
206.07845263682344 ---- 4.0
258.3051243175277 ---- 4.0
255.38020520349028 ---- 3.0
12.233063204290886 ---- 5.0
56.21749600848773 ---- 2.0
201.503526720866 ---- 3.0
201.3785950912209 ---- 4.0
201.5047686306048 ---- 4.0
535.2731490654721 ---- 5.0
207.0890510693167 ---- 2.0
263.5565640180599 ---- 3.0
245.40017634932025 ---- 2.0
215.1391251305798 ---- 4.0
118.47307553596544 ---- 4.0
225.89692204932675 ---- nan
72.71747854624282 ---- 4.0
126.31813932599913 ---- 5.0
101.46364521708966 ---- 4.0
158.18741393863226 ---- 3.0
381.46585666735086 ---- 2.0
5.0 ---- 4.0
218.62601903745133 ---- 2.0
5.0 ---- nan
102.80681342105666 ---- 4.0
258.8950596967366 ---- 5.0
156.42800190954628 ---- 3.0
42.22552220706939 ---- 4.0
78.46962907400318 ---- nan
217.9597748934676 ---- 4.0
76.96333682828633 ---- 3.0
171.6458589581975 ---- 4.0
154.5571839903814 ---- 3.0
84.83996523941829 ---- 3.0
364.3944089325325 ---- 5.0
213.3919022318011 ---- 5.0
nan ---- 4.0
168.64543147694278 ---- 5.0
83.8213535231612 ---- 4.0
235.2433334796224 ---- 5.0
70.74792615672993 ---- 4.0
138.5263558533101 ---- 3.0
200.49872789804573 ---- 5.0
236.57551941701212 ---- 5.0
29.97035929442238 ---- 4.0
116.54987641590516 ---- 5.0
102.50546888390438 ---- 3.0
84.66707674262881 ---- 5.0
326.54542402810966 ---- 1.0
190.49817109609555 ---- 3.0
23.911604566495484 ---- 5.0
241.7861947054776 ---- 4.0
362.21561970126334 ---- 4.0
253.24652605511469 ---- 2.0
5.0 ---- 5.0
101.57659271337486 ---- 5.0
276.69111491866227 ---- 4.0
79.23305343812193 ---- 3.0
nan ---- 5.0
227.4634053429337 ---- 5.0
57.306952842191706 ---- 5.0
144.04746439381998 ---- 5.0
5.0 ---- 3.0
47.56123586657101 ---- 3.0
124.74318486068395 ---- 3.0
25.22168180351505 ---- 4.0
313.2411303931636 ---- 4.0
6.985862203936733 ---- 4.0
105.99555133030162 ---- 5.0
163.07405772860915 ---- 5.0
294.1273289066115 ---- 2.0
6.413784882056064 ---- 3.0
266.31637521549595 ---- nan
151.0233061019587 ---- 3.0
51.84913489520491 ---- 3.0
196.21034742632708 ---- 5.0
169.905969557347 ---- 3.0
89.97831228412053 ---- 3.0
156.9802084990019 ---- 4.0
111.46864031382398 ---- 3.0
161.3517345251248 ---- 5.0
216.21306745210467 ---- 3.0
308.6016816145352 ---- 5.0
26.2184501173151 ---- 4.0
363.3033374656266 ---- 4.0
5.0 ---- 5.0
134.82149049644167 ---- 3.0
nan ---- 2.0
178.09918677350328 ---- 4.0
87.73004801794062 ---- 4.0
129.18777496427248 ---- 4.0
100.69990653411672 ---- 4.0
91.06352430557884 ---- 3.0
234.96020970210247 ---- 5.0
185.70154859650472 ---- 2.0
80.70904047393458 ---- 5.0
239.95998754332507 ---- 3.0
180.72995208766093 ---- 3.0
231.286211883896 ---- 3.0
212.96288419236123 ---- 3.0
67.10049890779277 ---- 4.0
93.98189598030304 ---- 5.0
224.7293605123262 ---- 4.0
211.03702654334649 ---- 4.0
147.9098406035852 ---- 3.0
161.7327383308782 ---- 4.0
277.7664895788425 ---- 5.0
90.842861116417 ---- 3.0
204.70973811700375 ---- 3.0
129.7807347566106 ---- 3.0
128.23187967727796 ---- 3.0
259.877685198719 ---- 1.0
232.54163489880295 ---- 4.0
231.35096360006384 ---- 3.0
280.54788071543294 ---- 2.0
152.10038416327592 ---- 5.0
218.1952971294964 ---- 3.0
118.9733243406544 ---- 3.0
182.41663524884424 ---- 5.0
136.98569456323153 ---- 2.0
159.69959649927182 ---- 2.0
209.51570254369136 ---- 4.0
68.17793167665275 ---- 5.0
359.238727568546 ---- 2.0
49.3982618500298 ---- 4.0
28.58113872122678 ---- 4.0
265.8110873500068 ---- 2.0
229.1662693962936 ---- 5.0
212.4119817052155 ---- 5.0
212.834550926428 ---- 3.0
148.77532271530853 ---- 5.0
60.274562851416846 ---- 5.0
157.58045581937265 ---- 4.0
82.28382884878883 ---- 3.0
247.5119733417751 ---- 3.0
135.29426184978612 ---- 4.0
67.45028032074885 ---- 4.0
117.86141583470068 ---- 3.0
191.2931454275624 ---- nan
93.62754471960253 ---- 5.0
67.77796044335686 ---- 4.0
174.36872114919123 ---- 3.0
174.49665711087226 ---- 5.0
nan ---- 5.0
102.89616943816772 ---- 1.0
173.20499373576362 ---- 4.0
5.19156585026758 ---- 2.0
9.253622562344477 ---- 4.0
78.1555778747564 ---- 4.0
128.65528482881527 ---- 4.0
181.09075655980047 ---- 3.0
297.53562169495524 ---- 2.0
235.76596232020196 ---- 3.0
134.00614700365728 ---- 4.0
148.09837920973112 ---- 5.0
nan ---- 3.0
148.148686400761 ---- 5.0
121.13413610798617 ---- nan
182.27185603380892 ---- 4.0
67.27690564476771 ---- 3.0
201.9346514241172 ---- 4.0
303.2738913002578 ---- 5.0
139.12398515431423 ---- 3.0
190.1711722098941 ---- 3.0
219.01439917111125 ---- 4.0
109.87795281141638 ---- 5.0
172.40924818104168 ---- 3.0
151.2592400781795 ---- 5.0
159.76760985488318 ---- 5.0
72.69902161445336 ---- 4.0
152.45101742589426 ---- 4.0
199.79982912454497 ---- 3.0
295.1143607795042 ---- 4.0
245.9270826085207 ---- 2.0
365.3182457511557 ---- nan
73.26524371119505 ---- 5.0
237.23206367206785 ---- 3.0
168.33420057383518 ---- 4.0
368.9802933217673 ---- 2.0
69.17017146448485 ---- 4.0
66.0278157819224 ---- 4.0
90.06073545559778 ---- 4.0
5.0 ---- 4.0
97.4244978319239 ---- 4.0
74.0867338446302 ---- 4.0
165.03937864762077 ---- 4.0
184.17559757771596 ---- 4.0
337.61708392158863 ---- 4.0
245.04238381860503 ---- 5.0
92.3096344337597 ---- 4.0
60.15853286516421 ---- 4.0
199.19191715065057 ---- nan
17.97667929793579 ---- 4.0
333.14587658543536 ---- 5.0
267.9440120721287 ---- 4.0
103.08243478952951 ---- 2.0
5.0 ---- 5.0
285.3872374165413 ---- 4.0
nan ---- 4.0
nan ---- 4.0
5.0 ---- 3.0
90.06249770462271 ---- 4.0
150.52436997181832 ---- 3.0
154.6980593764742 ---- 5.0
nan ---- 4.0
212.2849932347499 ---- 3.0
43.23795706174056 ---- 3.0
135.76205149787066 ---- 4.0
162.0295631711899 ---- 4.0
201.44388340587489 ---- 4.0
221.16148780888895 ---- 3.0
nan ---- 2.0
5.0 ---- 4.0
277.7676821898509 ---- 5.0
183.2314011979592 ---- 3.0
75.15134634434463 ---- nan
305.1151975522523 ---- 4.0
161.56746342928588 ---- 4.0
267.9297184063827 ---- nan
156.7518481410109 ---- 2.0
356.0747924881987 ---- 5.0
325.5340842443204 ---- 3.0
125.10358515209263 ---- 3.0
247.15709509543552 ---- 5.0
214.5375949585148 ---- 2.0
286.8631557532349 ---- 2.0
53.50765394198956 ---- 4.0
nan ---- 4.0
255.8424486849588 ---- 4.0
nan ---- 3.0
31.6741487334225 ---- 5.0
5.0 ---- 4.0
123.05931655554424 ---- 4.0
221.75422557959624 ---- 3.0
300.2357052096028 ---- 4.0
157.4094780419775 ---- 4.0
nan ---- 5.0
11.989854178510852 ---- 2.0
5.0 ---- 4.0
nan ---- 4.0
188.40654489393077 ---- 4.0
146.7305251905907 ---- 4.0
5.0 ---- 4.0
141.08799604872115 ---- 3.0
19.553049949514676 ---- 5.0
216.96725488300385 ---- 5.0
186.6598246096848 ---- 2.0
56.01202136726448 ---- 3.0
98.61330826633063 ---- 3.0
44.07864781110485 ---- 4.0
143.73209027268285 ---- 3.0
245.51423205012384 ---- 3.0
51.42739536644562 ---- 4.0
200.40465155178444 ---- 4.0
96.97423816275592 ---- 4.0
70.71271677376558 ---- 3.0
139.2969640045442 ---- 4.0
46.47576775806259 ---- 3.0
94.6350694652818 ---- nan
30.21221074111516 ---- 4.0
346.47251329163896 ---- 4.0
153.52635519717285 ---- 4.0
80.02744920074144 ---- 3.0
171.3979910734222 ---- 4.0
138.767195030917 ---- 4.0
127.9030400466777 ---- 2.0
211.4166700043425 ---- 3.0
225.7507710047305 ---- 4.0
96.94988523894725 ---- 3.0
92.418175935532 ---- 5.0
122.4948302848356 ---- 5.0
5.0 ---- 3.0
5.0 ---- 5.0
286.68742674445247 ---- 4.0
314.4967713501284 ---- 4.0
125.09639604436217 ---- 3.0
207.65569630557664 ---- 5.0
181.1250154543536 ---- 4.0
457.88808084552375 ---- 3.0
261.9574911434577 ---- 3.0
137.20824085192334 ---- 2.0
54.44595593995743 ---- 4.0
5.0 ---- 4.0
170.3463635867223 ---- 4.0
74.36492547156966 ---- 4.0
7.774629040232583 ---- 3.0
85.34271157574734 ---- 3.0
41.8451996385605 ---- 5.0
318.71416350725644 ---- 3.0
238.1639756949451 ---- 4.0
149.20273586833827 ---- 3.0
nan ---- 4.0
157.73683076476183 ---- 3.0
63.87157986717364 ---- 5.0
nan ---- nan
203.89100436846587 ---- 3.0
46.275384567354365 ---- 4.0
130.9661321916392 ---- 3.0
62.438174661524286 ---- 2.0
11.720026903566406 ---- nan
242.61775475316412 ---- 4.0
340.94166404701303 ---- nan
10.143242618085878 ---- 4.0
206.2969236690571 ---- 3.0
84.9357430878173 ---- 5.0
101.2874616235304 ---- 4.0
90.76060757611307 ---- 5.0
63.6009230320184 ---- 2.0
154.8521627944827 ---- 1.0
66.90498835889622 ---- 4.0
177.04568257798388 ---- 2.0
144.9761890550863 ---- 4.0
126.10519531335902 ---- 3.0
59.24363379584021 ---- 5.0
92.32286694316672 ---- 4.0
225.5391225825756 ---- 4.0
200.0917187624381 ---- 5.0
nan ---- 4.0
nan ---- 3.0
nan ---- 5.0
5.0 ---- 3.0
204.3360192379935 ---- 4.0
83.73762410541534 ---- 2.0
207.05986685931595 ---- 4.0
73.67408434574831 ---- 4.0
5.0 ---- 5.0
5.0 ---- 2.0
nan ---- 3.0
175.9722501721482 ---- 5.0
59.56833748955914 ---- 4.0
213.8592458777374 ---- 4.0
5.0 ---- 3.0
143.39202013526835 ---- 3.0
28.898380023754328 ---- 5.0
84.81638921978409 ---- 4.0
154.7398671316414 ---- 4.0
nan ---- 4.0
111.54444557701746 ---- 3.0
250.62928092144404 ---- nan
92.31081304768512 ---- 4.0
233.56921120651415 ---- 5.0
37.02931453423818 ---- 3.0
202.98041779152828 ---- 5.0
294.15686206579005 ---- 2.0
5.0 ---- 4.0
70.31047445295232 ---- nan
207.707212718054 ---- 2.0
129.69546139570073 ---- 4.0
187.1145873371309 ---- 3.0
89.60148132841795 ---- 3.0
nan ---- 4.0
134.43227646079205 ---- 5.0
266.77820616598075 ---- 4.0
175.4420843301213 ---- 4.0
183.7602662075202 ---- 4.0
108.81230338775326 ---- nan
101.23937759275064 ---- 3.0
106.74418121803792 ---- 5.0
189.44521423782967 ---- 4.0
107.9015519179737 ---- 4.0
178.9774856896413 ---- 3.0
nan ---- 3.0
nan ---- 4.0
117.39764678321588 ---- 2.0
270.1213922163945 ---- 2.0
109.19246269784486 ---- 3.0
5.0 ---- 4.0
49.19136890825959 ---- 3.0
5.0 ---- 3.0
114.84865159586914 ---- 3.0
151.84183791895518 ---- 3.0
317.6437312275283 ---- 3.0
182.69273737641623 ---- 5.0
128.08994711911356 ---- 5.0
232.9405581183489 ---- 5.0
5.0 ---- 5.0
nan ---- 3.0
227.08651938869667 ---- 3.0
5.0 ---- 3.0
264.3754043206929 ---- 5.0
183.84964074944145 ---- 3.0
108.47120860991988 ---- 3.0
213.2781866106285 ---- 3.0
377.0692857804396 ---- 4.0
nan ---- 4.0
174.8220586300336 ---- 4.0
104.0639100459756 ---- 3.0
65.01556305352082 ---- 4.0
233.03358165442452 ---- 3.0
64.39161740911328 ---- 4.0
157.15662372193924 ---- 4.0
nan ---- 3.0
197.8979825746392 ---- nan
183.36621052869484 ---- 4.0
253.75399442578995 ---- 3.0
98.9983601145253 ---- 3.0
123.01250647066288 ---- 4.0
52.12362842176927 ---- 5.0
nan ---- 4.0
187.7300493044852 ---- 4.0
225.6988616645352 ---- 4.0
57.78346758223746 ---- 3.0
236.960592010566 ---- 4.0
285.56378588049506 ---- 4.0
191.3434903223701 ---- 4.0
337.6795812558066 ---- 4.0
72.6210800896427 ---- 4.0
25.534529668858298 ---- nan
5.0 ---- 4.0
299.6044311489183 ---- 3.0
215.43656563540577 ---- 3.0
144.44153290895449 ---- 5.0
177.99686263198203 ---- 4.0
37.45109527016236 ---- 4.0
394.57519796168265 ---- 5.0
162.92211819752276 ---- 2.0
160.93947946048928 ---- 3.0
222.5766623898692 ---- nan
198.10092317367133 ---- 4.0
172.38840242791315 ---- 4.0
70.95255445546881 ---- 3.0
197.1468357135996 ---- 4.0
338.2024496475034 ---- 4.0
284.5420046154978 ---- nan
309.3186626639397 ---- 4.0
nan ---- 3.0
nan ---- 4.0
137.4213079900352 ---- 3.0
155.57249122886947 ---- 5.0
259.41915184709484 ---- 5.0
5.0 ---- 3.0
302.9550319460613 ---- 4.0
134.19921014210107 ---- 4.0
107.311893005258 ---- 3.0
48.78956247398325 ---- 3.0
5.0 ---- 4.0
232.31705839619144 ---- 5.0
157.3317967188404 ---- 5.0
21.00391002589461 ---- 5.0
20.4921227936384 ---- 4.0
116.4215300709872 ---- 3.0
316.90215252893927 ---- 4.0
124.04086486363953 ---- 5.0
5.0 ---- 3.0
125.42569359140558 ---- 4.0
122.72764302523296 ---- 5.0
5.0 ---- 5.0
144.57051334821878 ---- 5.0
126.9065469791322 ---- 4.0
219.62063648134185 ---- 5.0
334.8956094945345 ---- 3.0
262.65650295477576 ---- 5.0
123.11113094451694 ---- 4.0
39.34740912583297 ---- nan
407.33598032498605 ---- 5.0
155.92184340144885 ---- 3.0
151.39292919129463 ---- 4.0
147.58749128899967 ---- 4.0
169.8084760767855 ---- 3.0
135.56395880760576 ---- 4.0
92.63379931197638 ---- 2.0
95.3141058759608 ---- 5.0
146.72467297840015 ---- 4.0
95.6575228866235 ---- nan
78.71542173228356 ---- 3.0
160.64302276918968 ---- 4.0
124.50227825791448 ---- 4.0
300.3992988582688 ---- 4.0
5.0 ---- 3.0
259.15068519224616 ---- 3.0
274.60851924976294 ---- 4.0
5.0 ---- 3.0
115.73124059196512 ---- 4.0
112.85591340042086 ---- nan
9.248830528217866 ---- 4.0
72.21833124091248 ---- nan
38.94241545341713 ---- 3.0
325.22704434236226 ---- 2.0
nan ---- 3.0
277.15550949941587 ---- 5.0
222.1672064043235 ---- 5.0
37.094822878277085 ---- 5.0
97.54797337202262 ---- 4.0
198.93745612279184 ---- 2.0
27.787219110805463 ---- 1.0
221.2998430172388 ---- 3.0
125.96746018418648 ---- 4.0
112.51791924504025 ---- 5.0
221.09599682034917 ---- nan
nan ---- 4.0
113.903383418092 ---- 3.0
265.9329803364248 ---- 3.0
41.893667240010274 ---- 4.0
211.5935606944264 ---- 4.0
nan ---- 4.0
119.04535606860097 ---- 3.0
182.6133022242118 ---- 4.0
24.888642361469707 ---- 4.0
242.4027019206901 ---- 3.0
131.5097863557011 ---- 3.0
97.72769794809604 ---- nan
254.90092258368887 ---- 4.0
79.56563094572408 ---- 5.0
9.153870363644046 ---- 4.0
5.0 ---- 3.0
210.600995134564 ---- 4.0
21.9570647503717 ---- 4.0
325.47941819843646 ---- 3.0
5.0 ---- 3.0
319.6456368290038 ---- nan
171.10174672026184 ---- 5.0
140.32868881296076 ---- 4.0
nan ---- 5.0
189.9136114352071 ---- 3.0
146.23652975751517 ---- 5.0
260.33018820165216 ---- 3.0
nan ---- 3.0
165.03017614618776 ---- 2.0
113.6387787786144 ---- 3.0
144.30543762789324 ---- 3.0
180.7801768892059 ---- 4.0
5.0 ---- 4.0
15.181457789428691 ---- 3.0
224.3264094022715 ---- 3.0
167.0865438127942 ---- 3.0
131.6016663647321 ---- 2.0
151.84339330653933 ---- 3.0
nan ---- 3.0
96.02403196906386 ---- 5.0
72.16952745976873 ---- 4.0
169.58452550976816 ---- 4.0
52.1627222384968 ---- 2.0
190.8252755714472 ---- 5.0
5.0 ---- 5.0
252.91556373256435 ---- 2.0
197.2597482413043 ---- 3.0
175.60297343138757 ---- 4.0
248.2690983945514 ---- nan
316.54744444625766 ---- 3.0
251.43700650181304 ---- 3.0
5.0 ---- 3.0
22.042303326429845 ---- 4.0
87.51814223043212 ---- 5.0
152.60910502108337 ---- 3.0
201.7659020469123 ---- 5.0
77.42561868465344 ---- 3.0
168.67667644770785 ---- 3.0
74.46170676466775 ---- 5.0
nan ---- 5.0
9.333890315177769 ---- 5.0
57.67667538890957 ---- 2.0
14.831539438366631 ---- 3.0
52.41267470226673 ---- 5.0
255.36417966078395 ---- 4.0
55.0601111168057 ---- 3.0
413.2382064837391 ---- 4.0
199.3317900880889 ---- 3.0
nan ---- 5.0
64.16422198187864 ---- 5.0
220.03098794089917 ---- 4.0
92.4362173762226 ---- nan
162.20098146453614 ---- 4.0
406.0084538268795 ---- nan
140.39401002753502 ---- 5.0
264.9273326285676 ---- 4.0
79.68235748741125 ---- 4.0
146.50115095030384 ---- 2.0
327.080063563551 ---- 4.0
87.30329422122327 ---- 5.0
331.2448557996929 ---- 5.0
220.77519354554755 ---- 4.0
nan ---- 3.0
213.2407739055521 ---- 2.0
247.25544496267295 ---- 3.0
212.1809962217196 ---- 3.0
5.0 ---- 3.0
77.28628241751314 ---- 4.0
125.24813644484952 ---- 5.0
142.55665708999538 ---- 4.0

<ipython-input-58-6a6477b479ad>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(row[1][0],'----',row[1][1])